### ISSUE TITLE
Use @cucumber/cucumber instead of cucumber

### ISSUE THREAD

**Issue by stanecli** [timjroberts/cucumber-js-tsflow#74]
Hi.
Although it is quite unreasonable for me why they moved the package in the first place, the title says it all: the 'cucumber' package is deprecated, @cucumber/cucumber is the new one. The two versions are the same (7.0.0-rc.0), so it's not a show stopper, for now.. It's just quite frustrating when you just want to try something out and it doesn't work out of the box because of some import errors. Otherwise, it's a great project! :)
Cheers

**Comment by x80486** [comment]
Would be really great to update this one, even if it's on `-rc` for now :partying_face:

**Comment by timjroberts** [comment]
Could you elaborate a little more please? `cucumber-tsflow` doesn't have a direct dependency on cucumber. Technically it should be in its peer dependencies, but you essentially bring your own version of cucumber into your project.

**Comment by stanecli** [comment]
I can't give you more because I've completely rewritten the codebase for a PoC since this post and then moved on to specflow (for other technical reasons). If others will have a similar problem, someone will create an issue for sure. I'm closing this for now.

**Comment by x80486** [comment]
If you have a current project with `cucumber-tsflow` and update the `cucumber` dependency to `@cucumber/cucumber`, it won't work any more. It's that simple.

I see that somehow `cucumber-tsflow` is trying to reference some bits from `cucumber` instead of using `@cucumber/cucumber`.

**Comment by wudong** [comment]
There was a pr recently merged to update the dependency to @cucumber. But
it is not yet released due to the new version of cucumber is still in rc.

Maybe we should release a rc version as well to track this?

**Comment by timjroberts** [comment]
Right, I think I understand. Yes, `cucumber-tsflow` imports cucumber - but it's meant to be a peer (currently unspecified in the `package.json` file though). If they changed the package name of cucumber and that is what you bring into your project, then `cucumber-tsflow` won't be able to resolve it because it is still trying to import using the previous package name.

I can see this has been updated, but not release. So yes, perhaps we can release this as an `rc` too.
